import { FileDto } from "src/file/file.dto";
import { UserDto } from "src/user/user.dto";

export interface RhDto {
    id: number;
    disabled: boolean;
    date: Date;
    avatar?: FileDto;
    createdBy: UserDto;
    name?: string;
    surname?: string;
    birthDate?: Date;
    rg?: string;
    rgExpedicao?: string;
    rgOrgaoEmissor?: string;
    cnpj?: string;
    cnh?: string;
    gender?: string;
    civilState?: string;
    deficiency?: string;
    scholarship?: string;
    nacionality: string;
    naturality?: string;
    motherName?: string;
    fatherName?: string;
    cep?: string;
    street?: string;
    addressNumber?: string;
    addressComplement?: string;
    neighborhood?: string;
    city?: string;
    state?: string;
    telephone?: string;
    whatsapp?: string;
    emergencyTelephone?: string;
    personalEmail?: string;
    corporativeEmail?: string;
    department?: string;
    role?: string;
    contractType?: string;
    shift?: string;
    paycheck?: string;
    admission?: Date;
    experiencePeriod?: string;
    fireDate?: Date;
    pis?: string;
    mei?: string;
    bank?: string;
    bankAccountType?: string;
    bankAgency?: string;
    bankAccountNumber?: string;
}